smpl_publisher_node:
  ros__parameters:
    resolution: "2208x1242"
    # resolution: "1280x720"
    # resolution: "672x376"
    publish_image: true # whether to publish the original image
    publish_body: true # whether to publish the body keypoints and smpl parameters
    visualize_image: true