controller_manager:
  ros__parameters:
    thread_priority: 98
    update_rate: 1000  # Hz
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    right_gravity_compensation:
      type: gravity_compensation/GravityCompensation

    left_gravity_compensation:
      type: gravity_compensation/GravityCompensation

    left_cartesian_impedance_controller:
      type: cartesian_impedance_controller/CartesianImpedanceController
    
    right_cartesian_impedance_controller:
      type: cartesian_impedance_controller/CartesianImpedanceController
    
    left_motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle

    right_motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle


/**/right_gravity_compensation:
  ros__parameters:
    end_effector_link: "franka1_fr3_link0"
    ft_sensor_ref_link: "franka1_tcp" 
    robot_base_link: "world"
    compensate_gravity: false 
    compensate_coriolis: false 
    command_current_configuration: false
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - franka1_fr3_joint1
      - franka1_fr3_joint2
      - franka1_fr3_joint3
      - franka1_fr3_joint4
      - franka1_fr3_joint5
      - franka1_fr3_joint6
      - franka1_fr3_joint7

/**/left_gravity_compensation:
  ros__parameters:
    end_effector_link: "franka2_fr3_link0"
    ft_sensor_ref_link: "franka2_tcp" 
    robot_base_link: "world"
    compensate_gravity: false 
    compensate_coriolis: false 
    command_current_configuration: false
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - franka2_fr3_joint1
      - franka2_fr3_joint2
      - franka2_fr3_joint3
      - franka2_fr3_joint4
      - franka2_fr3_joint5
      - franka2_fr3_joint6
      - franka2_fr3_joint7

/**/left_cartesian_impedance_controller:
  ros__parameters:
    command_current_configuration: false # for KUKA set this to true, for other robots set to false
    max_impedance_force: 10.0 # (N) maximum task force
    delta_tau_max: 1.0 # (Nm) maximum torque increment in one control cycle
    stiffness:
        trans_x: 2000.0
        trans_y: 2000.0
        trans_z: 2000.0
        rot_x: 220.0
        rot_y: 220.0
        rot_z: 220.0
    nullspace_stiffness: 5.0
    nullspace_desired_configuration:
      - -1.39
      - 0.0
      - -0.35
      - -2.26
      - 0.0
      - 2.0
      - 1.0
    cartesian_impedance_controller:
      type: cartesian_impedance_controller/CartesianImpedanceController
    robot_base_link: "world"
    ft_sensor_ref_link: "franka2_tcp" 
    end_effector_link: "franka2_tcp"
    compensate_gravity: false 
    compensate_coriolis: false 
    command_current_configuration: false
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - franka2_fr3_joint1
      - franka2_fr3_joint2
      - franka2_fr3_joint3
      - franka2_fr3_joint4
      - franka2_fr3_joint5
      - franka2_fr3_joint6
      - franka2_fr3_joint7
    frame_topic_name: "/franka_left/desired_pose"

/**/right_cartesian_impedance_controller:
  ros__parameters:
    command_current_configuration: false # for KUKA set this to true, for other robots set to false
    max_impedance_force: 10.0 # (N) maximum task force
    delta_tau_max: 1.0 # (Nm) maximum torque increment in one control cycle
    stiffness:
        trans_x: 1700.0
        trans_y: 1700.0
        trans_z: 1400.0
        rot_x: 220.0
        rot_y: 220.0
        rot_z: 220.0
    nullspace_stiffness: 5.0
    nullspace_desired_configuration:
      - 0.5
      - 0.0
      - -0.35
      - -2.26
      - 0.0
      - 2.0
      - 1.0
    robot_base_link: "world"
    ft_sensor_ref_link: "franka1_tcp" 
    end_effector_link: "franka1_tcp"
    compensate_gravity: false 
    compensate_coriolis: false 
    command_current_configuration: false
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - franka1_fr3_joint1
      - franka1_fr3_joint2
      - franka1_fr3_joint3
      - franka1_fr3_joint4
      - franka1_fr3_joint5
      - franka1_fr3_joint6
      - franka1_fr3_joint7
    frame_topic_name: "/franka_right/desired_pose"


right_motion_control_handle:
  ros__parameters:
    robot_base_link: "world"
    end_effector_link: "franka1_tcp"
    target_frame_topic: "/franka_right/desired_pose"
    joints:
      - franka1_fr3_joint1
      - franka1_fr3_joint2
      - franka1_fr3_joint3
      - franka1_fr3_joint4
      - franka1_fr3_joint5
      - franka1_fr3_joint6
      - franka1_fr3_joint7

left_motion_control_handle:
  ros__parameters:
    robot_base_link: "world"
    end_effector_link: "franka2_tcp"
    target_frame_topic: "/franka_left/desired_pose"
    joints:
      - franka2_fr3_joint1
      - franka2_fr3_joint2
      - franka2_fr3_joint3
      - franka2_fr3_joint4
      - franka2_fr3_joint5
      - franka2_fr3_joint6
      - franka2_fr3_joint7
